name: brazilian_migration_analytics
version: '1.0'
config-version: 2
profile: brazilian_migration

model-paths: ["dbt/models"]
analysis-paths: []
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_modules"]

models:
  brazilian_migration_analytics:
    +materialized: view
    raw:
      +schema: raw
      +materialized: view
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table
